-- Database: GLOBALPLA Metadata version: 1 Exported: Sep 18, 2019
-- Begin Tables
SET LEGACYTYPESALLOWED = ON;
-- Begin Multi-Line Statement
CREATE TABLE "GCG_5259_COLUMNS" USING 'GCG_5259_COLUMNS007.mkd' PAGESIZE=4096 (
 "ID" IDENTITY DEFAULT '0' CONSTRAINT "UK_ID" UNIQUE USING 0,
 "JOB" CHAR(6),
 "SUFFIX" CHAR(3),
 "SEQ" CHAR(6),
 "ORDER_SORT" NUMERIC(4,0),
 "TOOL" CHAR(4),
 "GAGE" CHAR(4),
 "NOTES" CHAR(100),
 "QA" CHAR(10),
 "PALLET" CHAR(30),
 "PROGRAM" CHAR(30),
 "ACYT" CHAR(30),
 "SETUP_NOTE" CHAR(30),
 "RUNTIME_NOTE" CHAR(30) );
-- End Multi-Line Statement
ALTER TABLE "GCG_5259_COLUMNS" ADD CONSTRAINT "PK_ID" PRIMARY KEY  ( "ID" ) USING 0;
SET LEGACYTYPESALLOWED = OFF;
-- End Tables
